// window events
export const WINDOW_EVENTS = {
  CLOSE: 'CLOSE',

  TAB_CREATED: 'TAB_CREATED',
  NEW_TAB: 'NEW_TAB',
  SWITCH_TAB: 'SWITCH_TAB',
  CLOSE_TAB: 'CLOSE_TAB',
  SWAP_TAB: 'SWAP_TAB',
};

export const TAB_EVENTS = {
  UPDATE_TITLE: 'UPDATE_TITLE',
  UPDATE_FAVICON: 'UPDATE_FAVICON',
  UPDATE_LOADING: 'UPDATE_LOADING',
};

export const ADDRESS_BAR_EVENTS = {
  REQUEST_SUGGEST: 'REQUEST_SUGGEST',
};
