// window events
export const WINDOW_EVENTS = {
  CLOSE: 'CLOSE',

  TAB_CREATED: 'TAB_CREATED',
  NEW_TAB: 'NEW_TAB',
  NEW_TAB_TO_THE_RIGHT: 'NEW_TAB_TO_THE_RIGHT',
  SWITCH_TAB: 'SWITCH_TAB',
  CLOSE_TAB: 'CLOSE_TAB',
};

export const TAB_EVENTS = {
  UPDATE_TITLE: 'UPDATE_TITLE',
  UPDATE_FAVICON: 'UPDATE_FAVICON',
  UPDATE_LOADING: 'UPDATE_LOADING',
};
